language: android
android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - extra-android-support

before_install:
  - chmod +x gradlew

script:
  - ./gradlew assembleRelease

after_script:
 - du -a  |grep -i "*.apk"
 - du -a  /tmp |grep -i "*.apk"
 - sudo du -a / |grep -i "*.apk"
 - du -a
